apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: pensjon-saksbehandling
  name: "{{app.name}}"
  namespace: pensjon-saksbehandling
spec:
  ingresses:
    - "{{app.ingress}}"
  image: {{image}}
  port: 8080
  replicas:
    max: 2
    min: 2
  accessPolicy:
    outbound:
      rules:
        - application: "{{mock.name}}"
    inbound:
      rules:
        - application: "{{inbound.application.pensjon-pen.name}}"
          namespace: "{{inbound.application.pensjon-pen.namespace}}"
          cluster: "{{inbound.application.pensjon-pen.cluster}}"
  liveness:
    path: "/actuator/health/liveness"
    initialDelay: 10
  readiness:
    path: "/actuator/health/readiness"
    initialDelay: 10
  startup:
    path: "/actuator/health/readiness"
    initialDelay: 10
    failureThreshold: 100
    periodSeconds: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
  env:
    - name: "SPRING_PROFILES_ACTIVE"
      value: "{{env.name}}"
  azure:
    application:
      enabled: true
